import type { Product, Store } from './types'

export const STORES: Store[] = [
  { id: 'woolworths',        name: 'Woolworths',  color: '#1a8a2f' },
  { id: 'coles',             name: 'Coles',       color: '#cc1127' },
  { id: 'aldi',              name: 'Aldi',        color: '#003087' },
  { id: 'amazon',            name: 'Amazon AU',   color: '#e07b00' },
  { id: 'chemist_warehouse', name: 'Chemist Whs', color: '#0050a0' },
]

export const PRODUCTS: Product[] = [
  // ─── FORMULA ────────────────────────────────────────────────────────────────
  {
    id: 1, name: 'Aptamil Gold+ Stage 1 Infant Formula 900g',
    brand: 'Aptamil', category: 'Formula', size: '900g', abbr: 'AP1',
    imgBg: '#f0fdf4', imgFg: '#15803d', unitSize: 900, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 'aptamil', 'stage 1', 'infant formula', 'stage1'],
    prices: { woolworths: 38.00, coles: 36.00, aldi: null, amazon: 40.99, chemist_warehouse: 32.99 },
  },
  {
    id: 2, name: 'Aptamil Gold+ Stage 2 Follow-On Formula 900g',
    brand: 'Aptamil', category: 'Formula', size: '900g', abbr: 'AP2',
    imgBg: '#dcfce7', imgFg: '#15803d', unitSize: 900, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 'aptamil', 'stage 2', 'follow on', 'stage2'],
    prices: { woolworths: 38.00, coles: 36.00, aldi: null, amazon: 40.99, chemist_warehouse: 32.99 },
  },
  {
    id: 3, name: 'Karicare Gold+ Stage 1 Infant Formula 900g',
    brand: 'Karicare', category: 'Formula', size: '900g', abbr: 'KA1',
    imgBg: '#f0fdf4', imgFg: '#166534', unitSize: 900, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 'karicare', 'stage 1', 'infant formula'],
    prices: { woolworths: 40.00, coles: 38.00, aldi: null, amazon: 42.99, chemist_warehouse: 34.99 },
  },
  {
    id: 4, name: 'S-26 Original Stage 1 Infant Formula 900g',
    brand: 'S-26', category: 'Formula', size: '900g', abbr: 'S26',
    imgBg: '#f0fdf4', imgFg: '#166534', unitSize: 900, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 's-26', 's26', 'stage 1', 'infant formula'],
    prices: { woolworths: 33.00, coles: 31.00, aldi: null, amazon: 35.99, chemist_warehouse: 27.99 },
  },
  {
    id: 5, name: "Bellamy's Organic Stage 1 Infant Formula 900g",
    brand: "Bellamy's", category: 'Formula', size: '900g', abbr: 'BL1',
    imgBg: '#f0fdf4', imgFg: '#14532d', unitSize: 900, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 'bellamy', 'organic', 'stage 1'],
    prices: { woolworths: 41.00, coles: 39.00, aldi: null, amazon: 44.99, chemist_warehouse: 36.99 },
  },
  {
    id: 6, name: 'NAN Supreme Pro 1 Infant Formula 800g',
    brand: 'NAN', category: 'Formula', size: '800g', abbr: 'NAN',
    imgBg: '#f0fdf4', imgFg: '#14532d', unitSize: 800, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 'nan', 'supreme', 'stage 1'],
    prices: { woolworths: 37.00, coles: 35.00, aldi: null, amazon: 39.99, chemist_warehouse: 31.99 },
  },
  {
    id: 27, name: 'Aptamil Gold+ Stage 3 Toddler Milk Drink 900g',
    brand: 'Aptamil', category: 'Formula', size: '900g', abbr: 'AP3',
    imgBg: '#bbf7d0', imgFg: '#15803d', unitSize: 900, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 'aptamil', 'stage 3', 'toddler milk', 'stage3'],
    prices: { woolworths: 34.00, coles: 32.00, aldi: null, amazon: 36.99, chemist_warehouse: 28.99 },
  },
  {
    id: 28, name: 'Karicare Gold+ Stage 2 Follow-On Formula 900g',
    brand: 'Karicare', category: 'Formula', size: '900g', abbr: 'KA2',
    imgBg: '#dcfce7', imgFg: '#166534', unitSize: 900, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 'karicare', 'stage 2', 'follow on'],
    prices: { woolworths: 40.00, coles: 38.00, aldi: null, amazon: 42.99, chemist_warehouse: 34.99 },
  },
  {
    id: 29, name: 'NAN Comfort 1 Infant Formula 800g',
    brand: 'NAN', category: 'Formula', size: '800g', abbr: 'NC1',
    imgBg: '#f0fdf4', imgFg: '#166534', unitSize: 800, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 'nan', 'comfort', 'stage 1', 'colic'],
    prices: { woolworths: 36.00, coles: 34.00, aldi: null, amazon: 38.99, chemist_warehouse: 30.99 },
  },
  {
    id: 30, name: 'Aptamil Profutura Stage 1 Infant Formula 900g',
    brand: 'Aptamil', category: 'Formula', size: '900g', abbr: 'APF',
    imgBg: '#f0fdf4', imgFg: '#065f46', unitSize: 900, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 'aptamil', 'profutura', 'stage 1', 'premium'],
    prices: { woolworths: null, coles: null, aldi: null, amazon: 54.99, chemist_warehouse: 46.99 },
  },
  {
    id: 31, name: 'S-26 Gold Newborn Stage 1 Formula 800g',
    brand: 'S-26', category: 'Formula', size: '800g', abbr: 'SGN',
    imgBg: '#fefce8', imgFg: '#854d0e', unitSize: 800, unitStep: 100, unitLabel: '/100g',
    tags: ['formula', 's-26', 'gold', 'newborn', 'stage 1'],
    prices: { woolworths: 35.00, coles: 33.00, aldi: null, amazon: 37.99, chemist_warehouse: 29.99 },
  },

  // ─── NAPPIES ────────────────────────────────────────────────────────────────
  {
    id: 7, name: 'Huggies Ultra Dry Nappies Newborn 72pk',
    brand: 'Huggies', category: 'Nappies', size: '72 pk', abbr: 'HNB',
    imgBg: '#eff6ff', imgFg: '#1d4ed8', unitSize: 72, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'huggies', 'ultra dry', 'newborn', 'nappy'],
    prices: { woolworths: 24.00, coles: 22.00, aldi: null, amazon: 26.99, chemist_warehouse: null },
  },
  {
    id: 8, name: 'Huggies Ultra Dry Nappies Size 1 90pk',
    brand: 'Huggies', category: 'Nappies', size: '90 pk', abbr: 'HS1',
    imgBg: '#eff6ff', imgFg: '#1d4ed8', unitSize: 90, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'huggies', 'ultra dry', 'size 1', 'nappy'],
    prices: { woolworths: 26.00, coles: 24.00, aldi: null, amazon: 28.99, chemist_warehouse: null },
  },
  {
    id: 9, name: 'Huggies Ultra Dry Nappies Size 2 72pk',
    brand: 'Huggies', category: 'Nappies', size: '72 pk', abbr: 'HS2',
    imgBg: '#eff6ff', imgFg: '#1d4ed8', unitSize: 72, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'huggies', 'ultra dry', 'size 2', 'nappy'],
    prices: { woolworths: 22.00, coles: 20.00, aldi: null, amazon: 24.99, chemist_warehouse: null },
  },
  {
    id: 10, name: 'Pampers Baby Dry Nappies Size 1 88pk',
    brand: 'Pampers', category: 'Nappies', size: '88 pk', abbr: 'PM1',
    imgBg: '#eff6ff', imgFg: '#2563eb', unitSize: 88, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'pampers', 'baby dry', 'size 1', 'nappy'],
    prices: { woolworths: 27.00, coles: 25.00, aldi: null, amazon: 29.99, chemist_warehouse: 23.99 },
  },
  {
    id: 11, name: 'Pampers Baby Dry Nappies Size 2 80pk',
    brand: 'Pampers', category: 'Nappies', size: '80 pk', abbr: 'PM2',
    imgBg: '#eff6ff', imgFg: '#2563eb', unitSize: 80, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'pampers', 'baby dry', 'size 2', 'nappy'],
    prices: { woolworths: 25.00, coles: 23.00, aldi: null, amazon: 27.99, chemist_warehouse: 21.99 },
  },
  {
    id: 12, name: 'ALDI Mamia Nappies Size 1 52pk',
    brand: 'Mamia', category: 'Nappies', size: '52 pk', abbr: 'MA1',
    imgBg: '#eff6ff', imgFg: '#1e40af', unitSize: 52, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'aldi', 'mamia', 'size 1', 'nappy'],
    prices: { woolworths: null, coles: null, aldi: 10.99, amazon: null, chemist_warehouse: null },
  },
  {
    id: 32, name: 'Huggies Ultra Dry Nappies Size 3 60pk',
    brand: 'Huggies', category: 'Nappies', size: '60 pk', abbr: 'HS3',
    imgBg: '#eff6ff', imgFg: '#1d4ed8', unitSize: 60, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'huggies', 'ultra dry', 'size 3', 'nappy'],
    prices: { woolworths: 22.00, coles: 20.00, aldi: null, amazon: 24.99, chemist_warehouse: null },
  },
  {
    id: 33, name: 'Huggies Ultra Dry Nappies Size 4 52pk',
    brand: 'Huggies', category: 'Nappies', size: '52 pk', abbr: 'HS4',
    imgBg: '#eff6ff', imgFg: '#1d4ed8', unitSize: 52, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'huggies', 'ultra dry', 'size 4', 'nappy'],
    prices: { woolworths: 22.00, coles: 20.00, aldi: null, amazon: 24.99, chemist_warehouse: null },
  },
  {
    id: 34, name: 'Huggies Ultra Dry Nappies Size 5 48pk',
    brand: 'Huggies', category: 'Nappies', size: '48 pk', abbr: 'HS5',
    imgBg: '#eff6ff', imgFg: '#1d4ed8', unitSize: 48, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'huggies', 'ultra dry', 'size 5', 'nappy'],
    prices: { woolworths: 22.00, coles: 20.00, aldi: null, amazon: 24.99, chemist_warehouse: null },
  },
  {
    id: 35, name: 'Pampers Baby Dry Nappies Size 3 76pk',
    brand: 'Pampers', category: 'Nappies', size: '76 pk', abbr: 'PM3',
    imgBg: '#eff6ff', imgFg: '#2563eb', unitSize: 76, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'pampers', 'baby dry', 'size 3', 'nappy'],
    prices: { woolworths: 25.00, coles: 23.00, aldi: null, amazon: 27.99, chemist_warehouse: 21.99 },
  },
  {
    id: 36, name: 'Pampers Baby Dry Nappies Size 4 64pk',
    brand: 'Pampers', category: 'Nappies', size: '64 pk', abbr: 'PM4',
    imgBg: '#eff6ff', imgFg: '#2563eb', unitSize: 64, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'pampers', 'baby dry', 'size 4', 'nappy'],
    prices: { woolworths: 25.00, coles: 23.00, aldi: null, amazon: 27.99, chemist_warehouse: 21.99 },
  },
  {
    id: 37, name: 'ALDI Mamia Nappies Size 2 50pk',
    brand: 'Mamia', category: 'Nappies', size: '50 pk', abbr: 'MA2',
    imgBg: '#eff6ff', imgFg: '#1e40af', unitSize: 50, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'aldi', 'mamia', 'size 2', 'nappy'],
    prices: { woolworths: null, coles: null, aldi: 10.99, amazon: null, chemist_warehouse: null },
  },
  {
    id: 38, name: 'ALDI Mamia Nappies Size 3 48pk',
    brand: 'Mamia', category: 'Nappies', size: '48 pk', abbr: 'MA3',
    imgBg: '#eff6ff', imgFg: '#1e40af', unitSize: 48, unitStep: 1, unitLabel: '/nappy',
    tags: ['nappies', 'aldi', 'mamia', 'size 3', 'nappy'],
    prices: { woolworths: null, coles: null, aldi: 10.99, amazon: null, chemist_warehouse: null },
  },
  {
    id: 39, name: 'Huggies Pull-Ups Training Pants Size 3-4 20pk',
    brand: 'Huggies', category: 'Nappies', size: '20 pk', abbr: 'HPU',
    imgBg: '#eff6ff', imgFg: '#1d4ed8', unitSize: 20, unitStep: 1, unitLabel: '/pant',
    tags: ['nappies', 'huggies', 'pull-ups', 'training pants', 'toddler'],
    prices: { woolworths: 18.00, coles: 16.50, aldi: null, amazon: 19.99, chemist_warehouse: null },
  },

  // ─── BABY FOOD ──────────────────────────────────────────────────────────────
  {
    id: 13, name: "Rafferty's Garden Veg & Fruit Pouches 6x70g",
    brand: "Rafferty's", category: 'Baby Food', size: '6×70g', abbr: 'RG',
    imgBg: '#fefce8', imgFg: '#a16207', unitSize: 420, unitStep: 100, unitLabel: '/100g',
    tags: ['baby food', 'rafferty', 'pouch', 'vegetable', 'fruit'],
    prices: { woolworths: 7.50, coles: 7.00, aldi: 5.99, amazon: null, chemist_warehouse: null },
  },
  {
    id: 14, name: 'Heinz Baby Food Apple & Mango Pouches 4x120g',
    brand: 'Heinz', category: 'Baby Food', size: '4×120g', abbr: 'HZ',
    imgBg: '#fefce8', imgFg: '#92400e', unitSize: 480, unitStep: 100, unitLabel: '/100g',
    tags: ['baby food', 'heinz', 'pouch', 'apple', 'mango'],
    prices: { woolworths: 6.00, coles: 5.50, aldi: 4.99, amazon: null, chemist_warehouse: null },
  },
  {
    id: 15, name: 'Heinz Farex Infant Rice Cereal 125g',
    brand: 'Heinz', category: 'Baby Food', size: '125g', abbr: 'FR',
    imgBg: '#fefce8', imgFg: '#92400e', unitSize: 125, unitStep: 100, unitLabel: '/100g',
    tags: ['baby food', 'farex', 'rice cereal', 'cereal', 'heinz'],
    prices: { woolworths: 5.50, coles: 5.00, aldi: null, amazon: 7.99, chemist_warehouse: null },
  },
  {
    id: 16, name: 'Baby Mum-Mum Rice Rusks 36pk',
    brand: 'Mum-Mum', category: 'Baby Food', size: '36 pk', abbr: 'MM',
    imgBg: '#fefce8', imgFg: '#a16207', unitSize: 36, unitStep: 1, unitLabel: '/rusk',
    tags: ['baby food', 'mum mum', 'rice rusk', 'snack'],
    prices: { woolworths: 5.50, coles: 5.00, aldi: null, amazon: 6.99, chemist_warehouse: null },
  },
  {
    id: 40, name: 'Heinz Baby Food Chicken & Vegetable 120g',
    brand: 'Heinz', category: 'Baby Food', size: '120g', abbr: 'HZC',
    imgBg: '#fefce8', imgFg: '#b45309', unitSize: 120, unitStep: 100, unitLabel: '/100g',
    tags: ['baby food', 'heinz', 'chicken', 'vegetable', 'savoury'],
    prices: { woolworths: 2.50, coles: 2.20, aldi: null, amazon: null, chemist_warehouse: null },
  },
  {
    id: 41, name: "Rafferty's Garden Apple & Pear Pouches 6x70g",
    brand: "Rafferty's", category: 'Baby Food', size: '6×70g', abbr: 'RGA',
    imgBg: '#fef9c3', imgFg: '#a16207', unitSize: 420, unitStep: 100, unitLabel: '/100g',
    tags: ['baby food', 'rafferty', 'pouch', 'apple', 'pear', 'fruit'],
    prices: { woolworths: 7.50, coles: 7.00, aldi: 5.99, amazon: null, chemist_warehouse: null },
  },
  {
    id: 42, name: 'Little Bellies Organic Puffed Corn 6x7g',
    brand: 'Little Bellies', category: 'Baby Food', size: '6×7g', abbr: 'LB',
    imgBg: '#fefce8', imgFg: '#d97706', unitSize: 42, unitStep: 1, unitLabel: '/bag',
    tags: ['baby food', 'little bellies', 'organic', 'puffed corn', 'snack', 'toddler'],
    prices: { woolworths: 4.50, coles: 4.00, aldi: null, amazon: 5.99, chemist_warehouse: null },
  },
  {
    id: 43, name: 'Heinz Farex Wholegrain Oats Cereal 125g',
    brand: 'Heinz', category: 'Baby Food', size: '125g', abbr: 'FOC',
    imgBg: '#fef3c7', imgFg: '#92400e', unitSize: 125, unitStep: 100, unitLabel: '/100g',
    tags: ['baby food', 'farex', 'oats', 'cereal', 'heinz', 'wholegrain'],
    prices: { woolworths: 5.50, coles: 5.00, aldi: null, amazon: 7.49, chemist_warehouse: null },
  },
  {
    id: 44, name: 'Heinz Fruit & Veggie Snacks 7-Month 6x50g',
    brand: 'Heinz', category: 'Baby Food', size: '6×50g', abbr: 'HFS',
    imgBg: '#fefce8', imgFg: '#c2410c', unitSize: 300, unitStep: 100, unitLabel: '/100g',
    tags: ['baby food', 'heinz', 'snack', 'fruit', 'veggie', '7 month'],
    prices: { woolworths: 7.00, coles: 6.50, aldi: null, amazon: null, chemist_warehouse: null },
  },

  // ─── WIPES ──────────────────────────────────────────────────────────────────
  {
    id: 17, name: 'Huggies Baby Wipes Cucumber 200pk',
    brand: 'Huggies', category: 'Wipes', size: '200 pk', abbr: 'HW',
    imgBg: '#f0f9ff', imgFg: '#0369a1', unitSize: 200, unitStep: 100, unitLabel: '/100',
    tags: ['wipes', 'huggies', 'baby wipes', 'cucumber'],
    prices: { woolworths: 8.00, coles: 7.50, aldi: 6.99, amazon: 9.99, chemist_warehouse: null },
  },
  {
    id: 18, name: 'WaterWipes Original Baby Wipes 240pk',
    brand: 'WaterWipes', category: 'Wipes', size: '240 pk', abbr: 'WW',
    imgBg: '#f0f9ff', imgFg: '#0e7490', unitSize: 240, unitStep: 100, unitLabel: '/100',
    tags: ['wipes', 'waterwipes', 'water wipes', 'sensitive'],
    prices: { woolworths: 14.00, coles: 13.00, aldi: null, amazon: 15.99, chemist_warehouse: 12.99 },
  },
  {
    id: 19, name: 'Curash Fragrance Free Baby Wipes 252pk',
    brand: 'Curash', category: 'Wipes', size: '252 pk', abbr: 'CW',
    imgBg: '#f0f9ff', imgFg: '#0369a1', unitSize: 252, unitStep: 100, unitLabel: '/100',
    tags: ['wipes', 'curash', 'fragrance free', 'sensitive'],
    prices: { woolworths: 10.00, coles: 9.50, aldi: null, amazon: null, chemist_warehouse: 8.99 },
  },
  {
    id: 45, name: 'ALDI Mamia Baby Wipes Sensitive 80pk',
    brand: 'Mamia', category: 'Wipes', size: '80 pk', abbr: 'MAW',
    imgBg: '#f0f9ff', imgFg: '#1e40af', unitSize: 80, unitStep: 100, unitLabel: '/100',
    tags: ['wipes', 'mamia', 'aldi', 'sensitive', 'baby wipes'],
    prices: { woolworths: null, coles: null, aldi: 2.99, amazon: null, chemist_warehouse: null },
  },
  {
    id: 46, name: 'Huggies Natural Care Baby Wipes Aloe Vera 240pk',
    brand: 'Huggies', category: 'Wipes', size: '240 pk', abbr: 'HNC',
    imgBg: '#ecfdf5', imgFg: '#0369a1', unitSize: 240, unitStep: 100, unitLabel: '/100',
    tags: ['wipes', 'huggies', 'natural care', 'aloe vera', 'sensitive'],
    prices: { woolworths: 10.50, coles: 9.80, aldi: null, amazon: 12.99, chemist_warehouse: null },
  },
  {
    id: 47, name: 'Curash Micellar Baby Wipes 80pk',
    brand: 'Curash', category: 'Wipes', size: '80 pk', abbr: 'CMW',
    imgBg: '#f0f9ff', imgFg: '#0e7490', unitSize: 80, unitStep: 100, unitLabel: '/100',
    tags: ['wipes', 'curash', 'micellar', 'sensitive', 'baby wipes'],
    prices: { woolworths: 5.50, coles: 5.00, aldi: null, amazon: null, chemist_warehouse: 4.49 },
  },

  // ─── BATH & SKIN ────────────────────────────────────────────────────────────
  {
    id: 20, name: 'QV Baby Gentle Wash 500ml',
    brand: 'QV Baby', category: 'Bath & Skin', size: '500ml', abbr: 'QV',
    imgBg: '#fff7ed', imgFg: '#c2410c', unitSize: 500, unitStep: 100, unitLabel: '/100ml',
    tags: ['bath', 'wash', 'qv', 'baby wash', 'sensitive skin'],
    prices: { woolworths: 14.00, coles: 13.00, aldi: null, amazon: 15.99, chemist_warehouse: 10.99 },
  },
  {
    id: 21, name: "Johnson's Baby Wash & Shampoo 500ml",
    brand: "Johnson's", category: 'Bath & Skin', size: '500ml', abbr: 'JB',
    imgBg: '#fff7ed', imgFg: '#b45309', unitSize: 500, unitStep: 100, unitLabel: '/100ml',
    tags: ['bath', 'wash', 'shampoo', 'johnsons', 'baby wash'],
    prices: { woolworths: 8.00, coles: 7.50, aldi: null, amazon: 9.99, chemist_warehouse: 6.99 },
  },
  {
    id: 22, name: 'Bepanthen Nappy Rash Ointment 100g',
    brand: 'Bepanthen', category: 'Bath & Skin', size: '100g', abbr: 'BP',
    imgBg: '#fff7ed', imgFg: '#c2410c', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['nappy rash', 'bepanthen', 'ointment', 'cream', 'skin'],
    prices: { woolworths: 14.99, coles: 13.99, aldi: null, amazon: 16.99, chemist_warehouse: 11.99 },
  },
  {
    id: 23, name: 'Sudocrem Antiseptic Healing Cream 125g',
    brand: 'Sudocrem', category: 'Bath & Skin', size: '125g', abbr: 'SC',
    imgBg: '#fff7ed', imgFg: '#92400e', unitSize: 125, unitStep: 100, unitLabel: '/100g',
    tags: ['nappy rash', 'sudocrem', 'cream', 'antiseptic', 'skin'],
    prices: { woolworths: 10.00, coles: 9.50, aldi: null, amazon: 11.99, chemist_warehouse: 8.49 },
  },
  {
    id: 24, name: 'Aveeno Baby Daily Wash & Shampoo 354ml',
    brand: 'Aveeno', category: 'Bath & Skin', size: '354ml', abbr: 'AV',
    imgBg: '#fff7ed', imgFg: '#b45309', unitSize: 354, unitStep: 100, unitLabel: '/100ml',
    tags: ['bath', 'wash', 'aveeno', 'baby wash', 'sensitive'],
    prices: { woolworths: 16.00, coles: 15.00, aldi: null, amazon: 17.99, chemist_warehouse: 13.99 },
  },
  {
    id: 48, name: 'Mustela Gentle Cleansing Gel 500ml',
    brand: 'Mustela', category: 'Bath & Skin', size: '500ml', abbr: 'MU',
    imgBg: '#fdf4ff', imgFg: '#7e22ce', unitSize: 500, unitStep: 100, unitLabel: '/100ml',
    tags: ['bath', 'wash', 'mustela', 'gentle', 'sensitive skin'],
    prices: { woolworths: null, coles: null, aldi: null, amazon: 22.99, chemist_warehouse: 18.99 },
  },
  {
    id: 49, name: 'Cetaphil Baby Daily Lotion 400ml',
    brand: 'Cetaphil', category: 'Bath & Skin', size: '400ml', abbr: 'CL',
    imgBg: '#fff7ed', imgFg: '#9a3412', unitSize: 400, unitStep: 100, unitLabel: '/100ml',
    tags: ['bath', 'lotion', 'cetaphil', 'moisturiser', 'sensitive skin'],
    prices: { woolworths: 14.00, coles: 13.50, aldi: null, amazon: 16.99, chemist_warehouse: 11.99 },
  },
  {
    id: 50, name: "Johnson's Baby Lotion 500ml",
    brand: "Johnson's", category: 'Bath & Skin', size: '500ml', abbr: 'JBL',
    imgBg: '#fef9c3', imgFg: '#b45309', unitSize: 500, unitStep: 100, unitLabel: '/100ml',
    tags: ['bath', 'lotion', 'johnsons', 'moisturiser', 'baby skin'],
    prices: { woolworths: 7.50, coles: 7.00, aldi: null, amazon: 9.49, chemist_warehouse: 5.99 },
  },
  {
    id: 51, name: 'QV Baby Moisturising Cream 250g',
    brand: 'QV Baby', category: 'Bath & Skin', size: '250g', abbr: 'QVC',
    imgBg: '#fff7ed', imgFg: '#c2410c', unitSize: 250, unitStep: 100, unitLabel: '/100g',
    tags: ['bath', 'cream', 'qv', 'moisturiser', 'eczema', 'sensitive skin'],
    prices: { woolworths: 12.00, coles: 11.50, aldi: null, amazon: 13.99, chemist_warehouse: 9.49 },
  },

  // ─── HEALTH ─────────────────────────────────────────────────────────────────
  {
    id: 25, name: 'Nurofen for Children 3 Months+ 200ml',
    brand: 'Nurofen', category: 'Health', size: '200ml', abbr: 'NF',
    imgBg: '#fef2f2', imgFg: '#dc2626', unitSize: 200, unitStep: 100, unitLabel: '/100ml',
    tags: ['medicine', 'nurofen', 'ibuprofen', 'pain relief', 'fever', 'children'],
    prices: { woolworths: 13.99, coles: 13.99, aldi: null, amazon: 15.99, chemist_warehouse: 9.99 },
  },
  {
    id: 26, name: 'Panadol Baby & Infant Drops 20ml',
    brand: 'Panadol', category: 'Health', size: '20ml', abbr: 'PD',
    imgBg: '#fef2f2', imgFg: '#b91c1c', unitSize: 20, unitStep: 1, unitLabel: '/ml',
    tags: ['medicine', 'panadol', 'paracetamol', 'drops', 'pain relief', 'fever'],
    prices: { woolworths: 11.99, coles: 11.99, aldi: null, amazon: 13.99, chemist_warehouse: 9.49 },
  },
  {
    id: 52, name: "Infants' Friend Herbal Mixture 200ml",
    brand: "Infants' Friend", category: 'Health', size: '200ml', abbr: 'IF',
    imgBg: '#fef2f2', imgFg: '#9f1239', unitSize: 200, unitStep: 100, unitLabel: '/100ml',
    tags: ['medicine', 'infants friend', 'herbal', 'colic', 'wind', 'gripe'],
    prices: { woolworths: 12.99, coles: 12.99, aldi: null, amazon: 14.99, chemist_warehouse: 10.49 },
  },
  {
    id: 53, name: 'Colief Infant Drops 7ml',
    brand: 'Colief', category: 'Health', size: '7ml', abbr: 'COL',
    imgBg: '#fef2f2', imgFg: '#dc2626', unitSize: 7, unitStep: 1, unitLabel: '/ml',
    tags: ['medicine', 'colief', 'lactase', 'colic', 'drops', 'infant'],
    prices: { woolworths: null, coles: null, aldi: null, amazon: 29.99, chemist_warehouse: 24.99 },
  },
  {
    id: 54, name: 'Pentavite Multivitamin Liquid Drops 30ml',
    brand: 'Pentavite', category: 'Health', size: '30ml', abbr: 'PV',
    imgBg: '#fef2f2', imgFg: '#b91c1c', unitSize: 30, unitStep: 1, unitLabel: '/ml',
    tags: ['medicine', 'pentavite', 'multivitamin', 'vitamins', 'drops', 'infant'],
    prices: { woolworths: 14.99, coles: 14.99, aldi: null, amazon: 16.99, chemist_warehouse: 12.49 },
  },
  {
    id: 55, name: 'Brauer Baby & Toddler Probiotic 50ml',
    brand: 'Brauer', category: 'Health', size: '50ml', abbr: 'BR',
    imgBg: '#fef2f2', imgFg: '#9f1239', unitSize: 50, unitStep: 10, unitLabel: '/10ml',
    tags: ['medicine', 'brauer', 'probiotic', 'gut health', 'toddler'],
    prices: { woolworths: null, coles: null, aldi: null, amazon: 24.99, chemist_warehouse: 19.99 },
  },

  // ─── CHOCOLATES ─────────────────────────────────────────────────────────────
  {
    id: 56, name: 'Cadbury Dairy Milk Chocolate Block 180g',
    brand: 'Cadbury', category: 'Chocolates', size: '180g', abbr: 'CDM',
    imgBg: '#4c1d95', imgFg: '#c4b5fd', unitSize: 180, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'cadbury', 'dairy milk', 'block', 'milk chocolate'],
    prices: { woolworths: 5.00, coles: 5.00, aldi: 4.49, amazon: 6.49, chemist_warehouse: null },
  },
  {
    id: 57, name: 'Lindt Excellence 70% Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LDC',
    imgBg: '#1c1917', imgFg: '#d6d3d1', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'dark chocolate', '70%', 'block'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: null },
  },
  {
    id: 58, name: 'Kit Kat 4 Fingers Milk Chocolate 45g',
    brand: 'Kit Kat', category: 'Chocolates', size: '45g', abbr: 'KK',
    imgBg: '#dc2626', imgFg: '#fff', unitSize: 45, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'kit kat', 'wafer', 'bar', 'nestle'],
    prices: { woolworths: 2.00, coles: 2.00, aldi: null, amazon: 2.99, chemist_warehouse: null },
  },
  {
    id: 59, name: 'Cadbury Freddo Frogs Milk Chocolate 12pk',
    brand: 'Cadbury', category: 'Chocolates', size: '12×15g', abbr: 'FRD',
    imgBg: '#4c1d95', imgFg: '#e9d5ff', unitSize: 180, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'cadbury', 'freddo', 'milk chocolate', 'kids'],
    prices: { woolworths: 4.50, coles: 4.50, aldi: null, amazon: 5.99, chemist_warehouse: null },
  },
  {
    id: 60, name: 'Cadbury Caramello Koala Family Bag 162g',
    brand: 'Cadbury', category: 'Chocolates', size: '162g', abbr: 'CKO',
    imgBg: '#4c1d95', imgFg: '#fde68a', unitSize: 162, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'cadbury', 'caramello', 'koala', 'caramel'],
    prices: { woolworths: 5.00, coles: 5.00, aldi: null, amazon: 6.49, chemist_warehouse: null },
  },
  {
    id: 61, name: 'Kinder Surprise Eggs 3pk',
    brand: 'Kinder', category: 'Chocolates', size: '3×20g', abbr: 'KIN',
    imgBg: '#fef3c7', imgFg: '#b45309', unitSize: 60, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'kinder', 'surprise', 'egg', 'kids', 'toy'],
    prices: { woolworths: 8.00, coles: 8.00, aldi: null, amazon: 10.99, chemist_warehouse: null },
  },
  {
    id: 62, name: 'Ferrero Rocher Box 16pk 200g',
    brand: 'Ferrero Rocher', category: 'Chocolates', size: '200g', abbr: 'FR',
    imgBg: '#fef3c7', imgFg: '#92400e', unitSize: 200, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'ferrero', 'rocher', 'hazelnut', 'gift', 'luxury'],
    prices: { woolworths: 14.99, coles: 13.99, aldi: 9.99, amazon: 16.99, chemist_warehouse: null },
  },
  {
    id: 63, name: "M&M's Milk Chocolate Sharing Bag 200g",
    brand: "M&M's", category: 'Chocolates', size: '200g', abbr: 'MMC',
    imgBg: '#1d4ed8', imgFg: '#fbbf24', unitSize: 200, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'mms', 'm&ms', 'milk chocolate', 'sharing', 'mars'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.49, chemist_warehouse: null },
  },
  {
    id: 64, name: 'Snickers Bar 50g',
    brand: 'Snickers', category: 'Chocolates', size: '50g', abbr: 'SNK',
    imgBg: '#92400e', imgFg: '#fde68a', unitSize: 50, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'snickers', 'caramel', 'peanut', 'bar', 'mars'],
    prices: { woolworths: 2.50, coles: 2.50, aldi: null, amazon: 3.49, chemist_warehouse: null },
  },
  {
    id: 65, name: 'Mars Bar 53g',
    brand: 'Mars', category: 'Chocolates', size: '53g', abbr: 'MAR',
    imgBg: '#450a0a', imgFg: '#fca5a5', unitSize: 53, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'mars', 'caramel', 'nougat', 'bar'],
    prices: { woolworths: 2.50, coles: 2.50, aldi: null, amazon: 3.49, chemist_warehouse: null },
  },
  {
    id: 66, name: 'ALDI Moser Roth Dark Chocolate 125g',
    brand: 'Moser Roth', category: 'Chocolates', size: '125g', abbr: 'MRD',
    imgBg: '#1c1917', imgFg: '#a8a29e', unitSize: 125, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'moser roth', 'aldi', 'dark chocolate', 'block'],
    prices: { woolworths: null, coles: null, aldi: 2.99, amazon: null, chemist_warehouse: null },
  },
  {
    id: 67, name: 'Darrell Lea Milk Chocolate Block 185g',
    brand: 'Darrell Lea', category: 'Chocolates', size: '185g', abbr: 'DL',
    imgBg: '#7c3aed', imgFg: '#ede9fe', unitSize: 185, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'darrell lea', 'milk chocolate', 'block', 'australian'],
    prices: { woolworths: 5.00, coles: 5.00, aldi: null, amazon: 6.99, chemist_warehouse: null },
  },
  {
    id: 68, name: 'Cadbury Roses Chocolate Gift Box 250g',
    brand: 'Cadbury', category: 'Chocolates', size: '250g', abbr: 'CRS',
    imgBg: '#4c1d95', imgFg: '#f9a8d4', unitSize: 250, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'cadbury', 'roses', 'assorted', 'gift', 'box'],
    prices: { woolworths: 9.00, coles: 9.00, aldi: null, amazon: 12.99, chemist_warehouse: null },
  },

  // ─── LINDT EXCELLENCE (blocks) ──────────────────────────────────────────────
  {
    id: 69, name: 'Lindt Excellence 85% Cocoa Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'L85',
    imgBg: '#1c1917', imgFg: '#d6d3d1', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'dark chocolate', '85%', 'block'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },
  {
    id: 70, name: 'Lindt Excellence 90% Cocoa Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'L90',
    imgBg: '#0c0a09', imgFg: '#a8a29e', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'dark chocolate', '90%', 'block', 'intense'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },
  {
    id: 71, name: 'Lindt Excellence 95% Cocoa Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'L95',
    imgBg: '#0c0a09', imgFg: '#78716c', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'dark chocolate', '95%', 'block', 'intense'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },
  {
    id: 72, name: 'Lindt Excellence Extra Creamy Milk Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LEC',
    imgBg: '#78350f', imgFg: '#fde68a', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'milk chocolate', 'creamy', 'block'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },
  {
    id: 73, name: 'Lindt Excellence Caramel & Sea Salt Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LCS',
    imgBg: '#1c1917', imgFg: '#fde68a', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'caramel', 'sea salt', 'dark chocolate', 'block'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },
  {
    id: 74, name: 'Lindt Excellence Mint Intense Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LMI',
    imgBg: '#064e3b', imgFg: '#6ee7b7', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'mint', 'dark chocolate', 'block'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },
  {
    id: 75, name: 'Lindt Excellence Orange Intense Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LOI',
    imgBg: '#7c2d12', imgFg: '#fdba74', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'orange', 'dark chocolate', 'block'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },
  {
    id: 76, name: 'Lindt Excellence Chilli Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LCH',
    imgBg: '#7f1d1d', imgFg: '#fca5a5', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'chilli', 'dark chocolate', 'block', 'spicy'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },
  {
    id: 77, name: 'Lindt Excellence Raspberry Intense Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LRI',
    imgBg: '#881337', imgFg: '#fda4af', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'raspberry', 'dark chocolate', 'block'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },
  {
    id: 78, name: 'Lindt Excellence Sea Salt Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LSS',
    imgBg: '#1c1917', imgFg: '#e7e5e4', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'sea salt', 'dark chocolate', 'block'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },
  {
    id: 79, name: 'Lindt Excellence Smooth Mild Dark Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LSD',
    imgBg: '#292524', imgFg: '#d6d3d1', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'excellence', 'smooth', 'mild', 'dark chocolate', 'block'],
    prices: { woolworths: 5.50, coles: 5.50, aldi: null, amazon: 7.99, chemist_warehouse: 3.99 },
  },

  // ─── LINDT LINDOR (truffle bags) ────────────────────────────────────────────
  {
    id: 80, name: 'Lindt Lindor Milk Chocolate Truffles Bag 200g',
    brand: 'Lindt', category: 'Chocolates', size: '200g', abbr: 'LLM',
    imgBg: '#92400e', imgFg: '#fde68a', unitSize: 200, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'lindor', 'milk chocolate', 'truffles', 'bag'],
    prices: { woolworths: 10.00, coles: 10.00, aldi: null, amazon: 13.99, chemist_warehouse: 8.99 },
  },
  {
    id: 81, name: 'Lindt Lindor Dark Chocolate Truffles Bag 200g',
    brand: 'Lindt', category: 'Chocolates', size: '200g', abbr: 'LLD',
    imgBg: '#1c1917', imgFg: '#a8a29e', unitSize: 200, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'lindor', 'dark chocolate', 'truffles', 'bag'],
    prices: { woolworths: 10.00, coles: 10.00, aldi: null, amazon: 13.99, chemist_warehouse: 8.99 },
  },
  {
    id: 82, name: 'Lindt Lindor White Chocolate Truffles Bag 200g',
    brand: 'Lindt', category: 'Chocolates', size: '200g', abbr: 'LLW',
    imgBg: '#f5f0e8', imgFg: '#92400e', unitSize: 200, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'lindor', 'white chocolate', 'truffles', 'bag'],
    prices: { woolworths: 10.00, coles: 10.00, aldi: null, amazon: 13.99, chemist_warehouse: 8.99 },
  },
  {
    id: 83, name: 'Lindt Lindor Salted Caramel Truffles Bag 200g',
    brand: 'Lindt', category: 'Chocolates', size: '200g', abbr: 'LLSC',
    imgBg: '#78350f', imgFg: '#fcd34d', unitSize: 200, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'lindor', 'salted caramel', 'truffles', 'bag'],
    prices: { woolworths: 10.00, coles: 10.00, aldi: null, amazon: 13.99, chemist_warehouse: 8.99 },
  },
  {
    id: 84, name: 'Lindt Lindor Coconut Truffles Bag 200g',
    brand: 'Lindt', category: 'Chocolates', size: '200g', abbr: 'LLC',
    imgBg: '#d97706', imgFg: '#fef9c3', unitSize: 200, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'lindor', 'coconut', 'truffles', 'bag'],
    prices: { woolworths: 10.00, coles: 10.00, aldi: null, amazon: 13.99, chemist_warehouse: 8.99 },
  },
  {
    id: 85, name: 'Lindt Lindor Stracciatella Truffles Bag 200g',
    brand: 'Lindt', category: 'Chocolates', size: '200g', abbr: 'LLS',
    imgBg: '#f5f0e8', imgFg: '#1c1917', unitSize: 200, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'lindor', 'stracciatella', 'truffles', 'bag', 'white'],
    prices: { woolworths: 10.00, coles: 10.00, aldi: null, amazon: 13.99, chemist_warehouse: 8.99 },
  },
  {
    id: 86, name: 'Lindt Lindor Extra Dark 60% Truffles Bag 200g',
    brand: 'Lindt', category: 'Chocolates', size: '200g', abbr: 'LL6',
    imgBg: '#292524', imgFg: '#a8a29e', unitSize: 200, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'lindor', 'extra dark', '60%', 'truffles', 'bag'],
    prices: { woolworths: 10.00, coles: 10.00, aldi: null, amazon: 13.99, chemist_warehouse: 8.99 },
  },
  {
    id: 87, name: 'Lindt Lindor Assorted Truffles Bag 200g',
    brand: 'Lindt', category: 'Chocolates', size: '200g', abbr: 'LLA',
    imgBg: '#92400e', imgFg: '#fef3c7', unitSize: 200, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'lindor', 'assorted', 'truffles', 'bag', 'mixed'],
    prices: { woolworths: 10.00, coles: 10.00, aldi: null, amazon: 13.99, chemist_warehouse: 8.99 },
  },

  // ─── LINDT LINDOR (gift boxes) ──────────────────────────────────────────────
  {
    id: 88, name: 'Lindt Lindor Milk Chocolate Truffles Gift Box 337g',
    brand: 'Lindt', category: 'Chocolates', size: '337g', abbr: 'LLMB',
    imgBg: '#92400e', imgFg: '#fde68a', unitSize: 337, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'lindor', 'milk chocolate', 'truffles', 'box', 'gift'],
    prices: { woolworths: 22.00, coles: 22.00, aldi: null, amazon: 27.99, chemist_warehouse: 17.99 },
  },
  {
    id: 89, name: 'Lindt Lindor Assorted Truffles Gift Box 337g',
    brand: 'Lindt', category: 'Chocolates', size: '337g', abbr: 'LLAB',
    imgBg: '#78350f', imgFg: '#fef3c7', unitSize: 337, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'lindor', 'assorted', 'truffles', 'box', 'gift', 'mixed'],
    prices: { woolworths: 22.00, coles: 22.00, aldi: null, amazon: 27.99, chemist_warehouse: 17.99 },
  },

  // ─── LINDT SWISS CLASSIC ────────────────────────────────────────────────────
  {
    id: 90, name: 'Lindt Swiss Classic Milk Chocolate Block 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LSC',
    imgBg: '#92400e', imgFg: '#fef3c7', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'swiss classic', 'milk chocolate', 'block'],
    prices: { woolworths: 4.50, coles: 4.50, aldi: null, amazon: 6.99, chemist_warehouse: 3.49 },
  },
  {
    id: 91, name: 'Lindt Swiss Classic Hazelnut Milk Chocolate Block 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LSCH',
    imgBg: '#78350f', imgFg: '#fde68a', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'swiss classic', 'hazelnut', 'milk chocolate', 'block'],
    prices: { woolworths: 4.50, coles: 4.50, aldi: null, amazon: 6.99, chemist_warehouse: 3.49 },
  },
  {
    id: 92, name: 'Lindt Swiss Classic Caramel Milk Chocolate Block 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LSCC',
    imgBg: '#92400e', imgFg: '#fcd34d', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'swiss classic', 'caramel', 'milk chocolate', 'block'],
    prices: { woolworths: 4.50, coles: 4.50, aldi: null, amazon: 6.99, chemist_warehouse: 3.49 },
  },

  // ─── LINDT GOLD BUNNY ───────────────────────────────────────────────────────
  {
    id: 93, name: 'Lindt Gold Bunny Milk Chocolate 100g',
    brand: 'Lindt', category: 'Chocolates', size: '100g', abbr: 'LGB',
    imgBg: '#d97706', imgFg: '#fef9c3', unitSize: 100, unitStep: 100, unitLabel: '/100g',
    tags: ['chocolate', 'lindt', 'gold bunny', 'milk chocolate', 'easter', 'figurine'],
    prices: { woolworths: 9.00, coles: 9.00, aldi: null, amazon: 11.99, chemist_warehouse: 7.99 },
  },
]
